import type { Metadata } from "next";
import { LandingNav } from "@/components/landing/LandingNav";
import { Footer } from "@/components/landing/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern using Quizo.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-full flex-col">
      <LandingNav />
      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-16 md:px-8">
        <h1 className="text-3xl font-bold text-fg md:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-fg-secondary">Last updated: {LAST_UPDATED}</p>

        <div className="mt-8 space-y-8 text-fg-secondary [&_h2]:mb-2 [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-fg [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:space-y-1 [&_ul]:pl-6">
          <section>
            <p>
              By using Quizo, you agree to these terms. If you&apos;re an academy owner signing up
              on behalf of an organization, you&apos;re agreeing on that organization&apos;s behalf
              too.
            </p>
          </section>

          <section>
            <h2>What Quizo is</h2>
            <p>
              Quizo lets academies turn their own course material into adaptive quizzes, invite
              students to take them, and track results and certificates. There&apos;s a free plan
              and paid Pro/Institution plans with higher limits.
            </p>
          </section>

          <section>
            <h2>Your account</h2>
            <ul>
              <li>You&apos;re responsible for keeping your password secure and for activity under your account.</li>
              <li>Academy owners are responsible for the content their academy uploads and generates, and for who they invite as sub-admins or approve as students.</li>
              <li>You must be old enough to legally use online services in your country, or have a parent/guardian&apos;s permission where required.</li>
            </ul>
          </section>

          <section>
            <h2>AI-generated content</h2>
            <p>
              Quiz questions can be generated by AI (Google Gemini) from material an academy
              uploads. AI-generated questions are reviewed and approved by the academy before
              students ever see them, but AI can still make mistakes. Academies are responsible for
              reviewing generated questions before publishing a quiz, and Quizo doesn&apos;t
              guarantee the accuracy of AI-generated content.
            </p>
          </section>

          <section>
            <h2>Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Upload content you don&apos;t have the right to use.</li>
              <li>Try to access another academy&apos;s data, or another student&apos;s answers, outside of what the platform itself shows you.</li>
              <li>Use the anti-cheating detection features to harass or unfairly penalize a student.</li>
              <li>Attempt to disrupt, overload, or reverse-engineer the platform.</li>
            </ul>
          </section>

          <section>
            <h2>Plans, billing, and suspension</h2>
            <p>
              Free plan limits and paid plan pricing are shown on our{" "}
              <a href="/pricing" className="text-secondary underline">
                pricing page
              </a>
              . We can suspend an academy&apos;s access for violating these terms, non-payment on a
              paid plan, or activity that puts the platform or other academies at risk. We&apos;ll
              try to give notice first, except where immediate suspension is reasonably necessary.
            </p>
          </section>

          <section>
            <h2>Your content, your ownership</h2>
            <p>
              You keep ownership of the course material, questions, and branding you upload. You
              give us permission to store and process it only as needed to run the platform for you
              — we don&apos;t use one academy&apos;s content to train models or benefit another
              academy.
            </p>
          </section>

          <section>
            <h2>No warranty, limited liability</h2>
            <p>
              Quizo is provided &quot;as is.&quot; We work to keep it reliable, but we don&apos;t
              guarantee it will be error-free or uninterrupted. To the extent allowed by law, Quizo
              isn&apos;t liable for indirect or consequential damages arising from using the
              platform.
            </p>
          </section>

          <section>
            <h2>Changes to these terms</h2>
            <p>
              We may update these terms as the platform evolves. Meaningful changes will be
              reflected by an updated &quot;Last updated&quot; date on this page.
            </p>
          </section>

          <section>
            <h2>Contact</h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a href="mailto:support@example.com" className="text-secondary underline">
                support@example.com
              </a>
              .
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}

const LAST_UPDATED = "August 2026";
